# -*- coding: utf-8 -*-
"""python_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1462vMQyM04IT32N8q04HkgQhlKKX8GFD
"""

import pandas as pd
import numpy

data = pd.read_csv("/content/drive/MyDrive/SoftexRecife-logicaDeProgramacao/notas_alunos.csv")
 
def resultadoFinal(dataframe):

    media = (dataframe["nota1"] + dataframe["nota2"]) / 2
    dataframe = dataframe.assign(media = media)
    dataframe['situacao'] = ''

    dataframe.loc[(dataframe["media"] < 7) | (dataframe["faltas"] > 5),"situacao"] = "REPROVADO."
    dataframe.loc[(dataframe["media"] >= 7) & (dataframe["faltas"] < 5),"situacao"] = "APROVADO!"

    print(dataframe)
    maiorFalta = dataframe['faltas'].max()
    maiorMedia =dataframe['media'].max()
    mediatotal = [10, 10, 9, 8, 7, 0]

    print("A média total é: =",numpy.mean(mediatotal))
    print("A maior quantidade de faltas é: ",(maiorFalta))
    print("A maior média foi: ",(maiorMedia))
    
resultadoFinal(data)